title: Abdullah Al Rahat
description: Ph.D. Student in Computer Science at Georgia State University.
url: "https://rahatkutubi.github.io"
show_downloads: false
theme: jekyll-theme-minimal

author:
  name: Abdullah Al Rahat
  role: Ph.D. Student
  department: Department of Computer Science
  university: Georgia State University
  university_url: "https://www.gsu.edu/"
  advisor: Dr. Hemanth Venkateswara
  advisor_url: "#" # Add his website link here
  location: Atlanta, Georgia, USA
  email: rahatcse2k9@gmail.com
  github: rahatkutubi
  scholar: "https://scholar.google.com/citations?user=YOUR_ID"
  linkedin: "https://linkedin.com/in/YOUR_ID"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
exclude: [Gemfile, Gemfile.lock, node_modules, vendor]
