title: Abdullah Al Rahat
description: Ph.D. Student in Computer Science at Georgia State University.
url: "https://rahatkutubi.github.io"
show_downloads: false
theme: jekyll-theme-minimal

author:
  name: Abdullah Al Rahat
  role: Ph.D. Student
  department: Computer Science
  university: Georgia State University
  advisor: Dr. Hemanth Venkateswara
  email: rahatcse2k9@gmail.com
  github: rahatkutubi
  scholar: "https://scholar.google.com/citations?user=YOUR_ID"

# This tells Jekyll to read the _publications and _projects folders
collections:
  publications:
    output: true
    permalink: /publications/:path/
  projects:
    output: true

plugins:
  - jekyll-seo-tag

exclude: [Gemfile, Gemfile.lock, node_modules]
