# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------
title: Abdullah Al Rahat
description: Ph.D. Student in Computer Science at Georgia State University. Researching Generative AI, VLM, and Diffusion Models.
show_downloads: false # Removes the "Download ZIP" buttons
theme: jekyll-theme-minimal

# -----------------------------------------------------------------------------
# Author Information (SEO & Google Scholar)
# -----------------------------------------------------------------------------
author:
  name: Abdullah Al Rahat
  email: rahatcse2k9@gmail.com
  github: rahatkutubi

# -----------------------------------------------------------------------------
# Plugins & Build
# -----------------------------------------------------------------------------
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

